CREATE TABLE genre_tags (
    id TEXT PRIMARY KEY,
    label TEXT NOT NULL COLLATE NOCASE UNIQUE,
    icon TEXT NOT NULL,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE genre_tag_keywords (
    id TEXT PRIMARY KEY,
    genre_tag_id TEXT NOT NULL REFERENCES genre_tags(id) ON DELETE CASCADE,
    keyword TEXT NOT NULL
);

CREATE INDEX idx_genre_tag_keywords_tag ON genre_tag_keywords(genre_tag_id);

INSERT INTO genre_tags(id,label,icon) VALUES
    ('fantasy','Fantasy','sword'),
    ('science-fiction','Science Fiction','rocketLaunch'),
    ('mystery','Mystery','magnify'),
    ('romance','Romance','heartOutline'),
    ('horror','Horror','skullOutline'),
    ('classic-literature','Classic Literature','classics'),
    ('historical-fiction','Historical Fiction','castleOutline'),
    ('biography','Biography','accountBox'),
    ('poetry','Poetry','feather'),
    ('young-adult','Young Adult','schoolOutline'),
    ('children','Children''s','teddyBear'),
    ('thriller','Thriller','lightningBolt'),
    ('adventure','Adventure','compass'),
    ('humor','Humor','happyFace'),
    ('philosophy','Philosophy','lightbulb'),
    ('drama','Drama','dramaMasks'),
    ('non-fiction','Non-Fiction','fileDocument'),
    ('self-help','Self-Help','humanHandsUp'),
    ('science','Science','flask'),
    ('war','War','shieldSword');

INSERT INTO genre_tag_keywords(id,genre_tag_id,keyword) VALUES
    ('fantasy-1','fantasy','fantasy'),
    ('fantasy-2','fantasy','magic'),
    ('fantasy-3','fantasy','dragon'),
    ('fantasy-4','fantasy','mythical'),
    ('science-fiction-1','science-fiction','science fiction'),
    ('science-fiction-2','science-fiction','sci-fi'),
    ('science-fiction-3','science-fiction','space opera'),
    ('science-fiction-4','science-fiction','cyberpunk'),
    ('science-fiction-5','science-fiction','dystopian'),
    ('mystery-1','mystery','mystery'),
    ('mystery-2','mystery','detective'),
    ('mystery-3','mystery','crime fiction'),
    ('mystery-4','mystery','whodunit'),
    ('romance-1','romance','romance'),
    ('romance-2','romance','love stories'),
    ('romance-3','romance','romantic fiction'),
    ('horror-1','horror','horror'),
    ('horror-2','horror','ghost stories'),
    ('horror-3','horror','supernatural fiction'),
    ('classic-literature-1','classic-literature','classic literature'),
    ('classic-literature-2','classic-literature','literary classics'),
    ('classic-literature-3','classic-literature','classics'),
    ('historical-fiction-1','historical-fiction','historical fiction'),
    ('historical-fiction-2','historical-fiction','historical novel'),
    ('historical-fiction-3','historical-fiction','historical novels'),
    ('biography-1','biography','biography'),
    ('biography-2','biography','autobiography'),
    ('biography-3','biography','memoir'),
    ('poetry-1','poetry','poetry'),
    ('poetry-2','poetry','poems'),
    ('young-adult-1','young-adult','young adult'),
    ('young-adult-2','young-adult','teenagers'),
    ('children-1','children','children''s fiction'),
    ('children-2','children','juvenile literature'),
    ('children-3','children','children''s stories'),
    ('children-4','children','juvenile fiction'),
    ('thriller-1','thriller','thriller'),
    ('thriller-2','thriller','suspense'),
    ('thriller-3','thriller','espionage'),
    ('adventure-1','adventure','adventure stories'),
    ('adventure-2','adventure','adventure fiction'),
    ('adventure-3','adventure','pirate'),
    ('adventure-4','adventure','treasure'),
    ('adventure-5','adventure','pirates'),
    ('humor-1','humor','humor'),
    ('humor-2','humor','humour'),
    ('humor-3','humor','comedy'),
    ('philosophy-1','philosophy','philosophy'),
    ('philosophy-2','philosophy','ethics'),
    ('philosophy-3','philosophy','metaphysics'),
    ('drama-1','drama','drama'),
    ('drama-2','drama','plays'),
    ('non-fiction-1','non-fiction','non-fiction'),
    ('non-fiction-2','non-fiction','nonfiction'),
    ('self-help-1','self-help','self-help'),
    ('self-help-2','self-help','personal development'),
    ('science-1','science','popular science'),
    ('science-2','science','natural sciences'),
    ('science-3','science','scientific literature'),
    ('war-1','war','war stories'),
    ('war-2','war','military fiction'),
    ('war-3','war','world war');
