import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import type { ComponentProps } from 'react';
import { colors } from './theme';

type MaterialName = ComponentProps<typeof MaterialCommunityIcons>['name'];

const names = {
  home: 'home-variant-outline',
  libraries: 'bookshelf',
  collections: 'bookmark-multiple-outline',
  activity: 'bell-outline',
  search: 'magnify',
  contents: 'format-list-bulleted',
  discover: 'compass-outline',
  read: 'book-open-page-variant-outline',
  listen: 'headphones',
  synced: 'link-variant',
  account: 'account-circle-outline',
  devices: 'cellphone-link',
  enabled: 'check-circle-outline',
  disabled: 'cancel',
  play: 'play',
  pause: 'pause',
  sleepTimer: 'timer-sand',
  skipBack: 'rewind-15',
  skipForward: 'fast-forward-15',
  back: 'arrow-left',
  previousPage: 'chevron-left',
  nextPage: 'chevron-right',
  moveUp: 'arrow-up',
  moveDown: 'arrow-down',
  chevron: 'chevron-right',
  add: 'plus',
  decrease: 'minus',
  scroll: 'format-align-justify',
  users: 'account-group-outline',
  system: 'server-outline',
  backup: 'database-arrow-up-outline',
  report: 'file-document-outline',
  support: 'lifebuoy',
  privacy: 'shield-lock-outline',
  settings: 'cog-outline',
  folder: 'folder-outline',
  scan: 'refresh',
  import: 'tray-arrow-down',
  acquire: 'download-box-outline',
  bookmark: 'bookmark-outline',
  copy: 'content-copy',
  filter: 'filter-variant',
  send: 'send-outline',
  upload: 'tray-arrow-up',
  edit: 'pencil-outline',
  delete: 'trash-can-outline',
  more: 'dots-horizontal',
  check: 'check',
  warning: 'alert-outline',
  error: 'alert-circle-outline',
  close: 'close',
  shelfLayout: 'view-day-outline',
  gridLayout: 'view-grid-outline',
  genres: 'tag-multiple-outline',
  sword: 'sword',
  rocketLaunch: 'rocket-launch-outline',
  magnify: 'magnify',
  heartOutline: 'heart-outline',
  skullOutline: 'skull-outline',
  classics: 'bookshelf',
  castleOutline: 'castle',
  accountBox: 'account-box-outline',
  feather: 'feather',
  schoolOutline: 'account-school-outline',
  teddyBear: 'teddy-bear',
  lightningBolt: 'lightning-bolt-outline',
  compass: 'compass-outline',
  happyFace: 'emoticon-happy-outline',
  lightbulb: 'lightbulb-outline',
  dramaMasks: 'drama-masks',
  fileDocument: 'file-document-outline',
  humanHandsUp: 'human-handsup',
  flask: 'flask-outline',
  shieldSword: 'shield-sword-outline',
  airplane: 'airplane',
  alien: 'alien-outline',
  atom: 'atom',
  baby: 'baby-face-outline',
  bank: 'bank-outline',
  bird: 'bird',
  butterfly: 'butterfly-outline',
  camera: 'camera-outline',
  cat: 'cat',
  chefHat: 'chef-hat',
  city: 'city-variant-outline',
  crown: 'crown-outline',
  earth: 'earth',
  familyTree: 'family-tree',
  film: 'filmstrip',
  fire: 'fire',
  flower: 'flower-outline',
  game: 'gamepad-variant-outline',
  ghost: 'ghost-outline',
  guitar: 'guitar-acoustic',
  history: 'history',
  leaf: 'leaf',
  medical: 'medical-bag',
  music: 'music-note-outline',
  palette: 'palette-outline',
  paw: 'paw-outline',
  pirate: 'pirate',
  robot: 'robot-outline',
  shipWheel: 'ship-wheel',
  star: 'star-outline',
  tree: 'tree-outline',
} satisfies Record<string, MaterialName>;

export type AppIconName = keyof typeof names;

export const genreIconOptions: { value: AppIconName; label: string }[] = [
  { value: 'genres', label: 'Tag' },
  { value: 'sword', label: 'Sword' },
  { value: 'rocketLaunch', label: 'Rocket' },
  { value: 'magnify', label: 'Mystery' },
  { value: 'heartOutline', label: 'Romance' },
  { value: 'skullOutline', label: 'Horror' },
  { value: 'classics', label: 'Classics' },
  { value: 'castleOutline', label: 'Castle' },
  { value: 'accountBox', label: 'Biography' },
  { value: 'feather', label: 'Poetry' },
  { value: 'schoolOutline', label: 'Education' },
  { value: 'teddyBear', label: 'Children' },
  { value: 'lightningBolt', label: 'Thriller' },
  { value: 'compass', label: 'Adventure' },
  { value: 'happyFace', label: 'Humor' },
  { value: 'lightbulb', label: 'Ideas' },
  { value: 'dramaMasks', label: 'Drama' },
  { value: 'fileDocument', label: 'Non-fiction' },
  { value: 'humanHandsUp', label: 'Self-help' },
  { value: 'flask', label: 'Science' },
  { value: 'shieldSword', label: 'War' },
  { value: 'airplane', label: 'Travel' },
  { value: 'alien', label: 'Alien' },
  { value: 'atom', label: 'Physics' },
  { value: 'baby', label: 'Baby' },
  { value: 'bank', label: 'Politics' },
  { value: 'bird', label: 'Bird' },
  { value: 'butterfly', label: 'Butterfly' },
  { value: 'camera', label: 'Photography' },
  { value: 'cat', label: 'Cat' },
  { value: 'chefHat', label: 'Cooking' },
  { value: 'city', label: 'City' },
  { value: 'crown', label: 'Royalty' },
  { value: 'earth', label: 'World' },
  { value: 'familyTree', label: 'Family' },
  { value: 'film', label: 'Film' },
  { value: 'fire', label: 'Fire' },
  { value: 'flower', label: 'Flower' },
  { value: 'game', label: 'Games' },
  { value: 'ghost', label: 'Ghost' },
  { value: 'guitar', label: 'Guitar' },
  { value: 'history', label: 'History' },
  { value: 'leaf', label: 'Nature' },
  { value: 'medical', label: 'Health' },
  { value: 'music', label: 'Music' },
  { value: 'palette', label: 'Art' },
  { value: 'paw', label: 'Animals' },
  { value: 'pirate', label: 'Pirates' },
  { value: 'robot', label: 'Technology' },
  { value: 'shipWheel', label: 'Nautical' },
  { value: 'star', label: 'Star' },
  { value: 'tree', label: 'Outdoors' },
];

export function isAppIconName(name: string): name is AppIconName {
  return Object.prototype.hasOwnProperty.call(names, name);
}

export function AppIcon({
  name,
  size = 20,
  color = colors.ink,
}: {
  name: AppIconName;
  size?: number;
  color?: string;
}) {
  return (
    <MaterialCommunityIcons
      accessibilityElementsHidden
      importantForAccessibility="no-hide-descendants"
      name={names[name]}
      size={size}
      color={color}
    />
  );
}
