package acquisition

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"sort"
	"strings"
)

func (c *Client) Search(ctx context.Context, query string) ([]Result, error) {
	report, err := c.SearchReport(ctx, query)
	return report.Results, err
}

func (c *Client) SearchReport(ctx context.Context, query string) (SearchReport, error) {
	query = strings.TrimSpace(query)
	if c.options.IndexerURL == "" || query == "" {
		return SearchReport{}, ErrUnavailable
	}

	if c.options.IndexerKind == "prowlarr" {
		return c.searchProwlarr(ctx, query)
	}

	results, excluded, err := c.searchFeedReport(ctx, c.options.IndexerURL, query, "")
	outcome := IndexerOutcome{Name: "Torznab", Results: len(results), Excluded: excluded}
	if err != nil {
		outcome.Error = searchDiagnostic(err)
		if ctx.Err() == nil {
			err = fmt.Errorf("%w: Torznab unavailable", ErrSearchFailed)
		}
	}

	return SearchReport{
		Results:   results,
		Indexers:  []IndexerOutcome{outcome},
		Reachable: err == nil,
	}, err
}

func (c *Client) Indexers(ctx context.Context) ([]Indexer, error) {
	if c.options.IndexerKind != "prowlarr" || c.options.IndexerURL == "" {
		return nil, ErrUnavailable
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodGet, strings.TrimRight(c.options.IndexerURL, "/")+"/api/v1/indexer", nil)
	if err != nil {
		return nil, fmt.Errorf("build Prowlarr request: %w", err)
	}

	req.Header.Set("X-Api-Key", c.options.IndexerAPIKey)
	response, err := c.http.Do(req)
	if err != nil {
		return nil, errors.New("connect to Prowlarr: request failed")
	}

	defer response.Body.Close()

	if response.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("connect to Prowlarr: status %d", response.StatusCode)
	}

	var raw []struct {
		ID       int    `json:"id"`
		Name     string `json:"name"`
		Protocol string `json:"protocol"`
		Enable   bool   `json:"enable"`
	}
	if err := json.NewDecoder(io.LimitReader(response.Body, 2<<20)).Decode(&raw); err != nil {
		return nil, fmt.Errorf("read Prowlarr indexers: %w", err)
	}

	result := make([]Indexer, 0, len(raw))
	for _, value := range raw {
		if value.ID > 0 && strings.TrimSpace(value.Name) != "" {
			result = append(result, Indexer{
				ID:       value.ID,
				Name:     strings.TrimSpace(value.Name),
				Protocol: strings.ToLower(value.Protocol),
				Enabled:  value.Enable,
			})
		}
	}

	return result, nil
}

func (c *Client) searchProwlarr(ctx context.Context, query string) (SearchReport, error) {
	indexers, err := c.Indexers(ctx)
	if err != nil {
		if ctx.Err() != nil {
			return SearchReport{}, ctx.Err()
		}

		return SearchReport{}, fmt.Errorf("%w: cannot reach Prowlarr", ErrSearchFailed)
	}

	type response struct {
		values  []Result
		outcome IndexerOutcome
	}
	results := make(chan response, len(indexers))
	semaphore := make(chan struct{}, 4)
	var count int
	for _, indexer := range indexers {
		if !indexer.Enabled || indexer.Protocol != "torrent" {
			continue
		}

		count++
		semaphore <- struct{}{}
		go func(value Indexer) {
			defer func() { <-semaphore }()

			feed := fmt.Sprintf("%s/%d/api", strings.TrimRight(c.options.IndexerURL, "/"), value.ID)
			items, excluded, err := c.searchFeedReport(ctx, feed, query, safeIndexerName(value.Name, c.options.IndexerAPIKey))
			for i := range items {
				items[i].Metadata.IndexerID = value.ID
			}

			outcome := IndexerOutcome{
				ID:       value.ID,
				Name:     safeIndexerName(value.Name, c.options.IndexerAPIKey),
				Results:  len(items),
				Excluded: excluded,
			}
			if err != nil {
				outcome.Error = searchDiagnostic(err)
			}

			results <- response{values: items, outcome: outcome}
		}(indexer)
	}

	report := SearchReport{Reachable: true}
	successes := 0
	for range count {
		value := <-results
		report.Results = append(report.Results, value.values...)
		report.Indexers = append(report.Indexers, value.outcome)
		if value.outcome.Error == "" {
			successes++
		}
	}

	sort.Slice(report.Indexers, func(i, j int) bool {
		return report.Indexers[i].Name < report.Indexers[j].Name
	})
	if err := ctx.Err(); err != nil {
		return report, err
	}

	if count == 0 {
		return report, fmt.Errorf("%w: Prowlarr has no enabled torrent indexers", ErrSearchFailed)
	}

	if successes == 0 {
		return report, fmt.Errorf("%w: all enabled indexers failed. Check Connections.", ErrSearchFailed)
	}

	return report, nil
}

func searchDiagnostic(err error) string {
	if errors.Is(err, context.DeadlineExceeded) {
		return "Search timed out. Retry or check the indexer."
	}

	// These status errors contain only the HTTP status generated by searchFeed.
	if strings.HasPrefix(err.Error(), "search indexer: status ") {
		return err.Error() + ". Check the indexer connection and API key."
	}

	if strings.HasPrefix(err.Error(), "parse indexer response:") {
		return "The indexer returned an invalid feed."
	}

	return "Search failed. Check the indexer connection and API key."
}

func safeIndexerName(name, apiKey string) string {
	if apiKey != "" {
		name = strings.ReplaceAll(name, apiKey, "[redacted]")
	}

	if strings.Contains(name, "://") || strings.Contains(name, "?") {
		return "Indexer"
	}

	runes := []rune(strings.Join(strings.Fields(name), " "))
	return string(runes[:min(80, len(runes))])
}
