// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: alignment_jobs.sql

package dbsql

import (
	"context"
	"database/sql"
)

const listAlignmentJobsForWork = `-- name: ListAlignmentJobsForWork :many
SELECT j.id,
       COALESCE(j.alignment_id, '') AS alignment_id,
       j.epub_media_id,
       j.audio_media_id,
       j.state,
       j.attempts,
       j.worker_version,
       j.model,
       COALESCE(j.artifact_id, '') AS artifact_id,
       j.error_summary,
       j.created_at,
       j.started_at,
       j.finished_at
FROM alignment_jobs j
JOIN media epub ON epub.id = j.epub_media_id
JOIN representations representation ON representation.id = epub.representation_id
JOIN media audio ON audio.id = j.audio_media_id
JOIN representations audio_representation ON audio_representation.id = audio.representation_id
WHERE representation.work_id = ?
  AND audio_representation.work_id = representation.work_id
ORDER BY j.created_at DESC, j.id DESC
LIMIT ? OFFSET ?
`

type ListAlignmentJobsForWorkParams struct {
	WorkID string
	Limit  int64
	Offset int64
}

type ListAlignmentJobsForWorkRow struct {
	ID            string
	AlignmentID   string
	EpubMediaID   string
	AudioMediaID  string
	State         string
	Attempts      int64
	WorkerVersion string
	Model         string
	ArtifactID    string
	ErrorSummary  string
	CreatedAt     string
	StartedAt     sql.NullString
	FinishedAt    sql.NullString
}

func (q *Queries) ListAlignmentJobsForWork(ctx context.Context, arg ListAlignmentJobsForWorkParams) ([]ListAlignmentJobsForWorkRow, error) {
	rows, err := q.db.QueryContext(ctx, listAlignmentJobsForWork, arg.WorkID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAlignmentJobsForWorkRow{}
	for rows.Next() {
		var i ListAlignmentJobsForWorkRow
		if err := rows.Scan(
			&i.ID,
			&i.AlignmentID,
			&i.EpubMediaID,
			&i.AudioMediaID,
			&i.State,
			&i.Attempts,
			&i.WorkerVersion,
			&i.Model,
			&i.ArtifactID,
			&i.ErrorSummary,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
