// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: genre_tags.sql

package dbsql

import (
	"context"
)

const createGenreTag = `-- name: CreateGenreTag :exec
INSERT INTO genre_tags(id, label, icon) VALUES (?, ?, ?)
`

type CreateGenreTagParams struct {
	ID    string
	Label string
	Icon  string
}

func (q *Queries) CreateGenreTag(ctx context.Context, arg CreateGenreTagParams) error {
	_, err := q.db.ExecContext(ctx, createGenreTag, arg.ID, arg.Label, arg.Icon)
	return err
}

const createGenreTagKeyword = `-- name: CreateGenreTagKeyword :exec
INSERT INTO genre_tag_keywords(id, genre_tag_id, keyword) VALUES (?, ?, ?)
`

type CreateGenreTagKeywordParams struct {
	ID         string
	GenreTagID string
	Keyword    string
}

func (q *Queries) CreateGenreTagKeyword(ctx context.Context, arg CreateGenreTagKeywordParams) error {
	_, err := q.db.ExecContext(ctx, createGenreTagKeyword, arg.ID, arg.GenreTagID, arg.Keyword)
	return err
}

const deleteGenreTag = `-- name: DeleteGenreTag :execrows
DELETE FROM genre_tags WHERE id = ?
`

func (q *Queries) DeleteGenreTag(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGenreTag, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteGenreTagKeywords = `-- name: DeleteGenreTagKeywords :exec
DELETE FROM genre_tag_keywords WHERE genre_tag_id = ?
`

func (q *Queries) DeleteGenreTagKeywords(ctx context.Context, genreTagID string) error {
	_, err := q.db.ExecContext(ctx, deleteGenreTagKeywords, genreTagID)
	return err
}

const listGenreTags = `-- name: ListGenreTags :many
SELECT t.id, t.label, t.icon, t.created_at, COALESCE(k.keyword, '') AS keyword
FROM genre_tags t
LEFT JOIN genre_tag_keywords k ON k.genre_tag_id = t.id
ORDER BY t.label COLLATE NOCASE, k.keyword COLLATE NOCASE
`

type ListGenreTagsRow struct {
	ID        string
	Label     string
	Icon      string
	CreatedAt string
	Keyword   string
}

func (q *Queries) ListGenreTags(ctx context.Context) ([]ListGenreTagsRow, error) {
	rows, err := q.db.QueryContext(ctx, listGenreTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGenreTagsRow{}
	for rows.Next() {
		var i ListGenreTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Icon,
			&i.CreatedAt,
			&i.Keyword,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGenreTag = `-- name: UpdateGenreTag :execrows
UPDATE genre_tags SET label = ?, icon = ? WHERE id = ?
`

type UpdateGenreTagParams struct {
	Label string
	Icon  string
	ID    string
}

func (q *Queries) UpdateGenreTag(ctx context.Context, arg UpdateGenreTagParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGenreTag, arg.Label, arg.Icon, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
