// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: narrators.sql

package dbsql

import (
	"context"
)

const deleteRepresentationNarrators = `-- name: DeleteRepresentationNarrators :exec
DELETE FROM representation_narrators WHERE representation_id = ?
`

func (q *Queries) DeleteRepresentationNarrators(ctx context.Context, representationID string) error {
	_, err := q.db.ExecContext(ctx, deleteRepresentationNarrators, representationID)
	return err
}

const insertRepresentationNarrator = `-- name: InsertRepresentationNarrator :exec
INSERT INTO representation_narrators(representation_id,ordinal,name,name_key) VALUES(?,?,?,?)
`

type InsertRepresentationNarratorParams struct {
	RepresentationID string
	Ordinal          int64
	Name             string
	NameKey          string
}

func (q *Queries) InsertRepresentationNarrator(ctx context.Context, arg InsertRepresentationNarratorParams) error {
	_, err := q.db.ExecContext(ctx, insertRepresentationNarrator,
		arg.RepresentationID,
		arg.Ordinal,
		arg.Name,
		arg.NameKey,
	)
	return err
}

const representationNarrators = `-- name: RepresentationNarrators :many
SELECT name FROM representation_narrators WHERE representation_id = ? ORDER BY ordinal
`

func (q *Queries) RepresentationNarrators(ctx context.Context, representationID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, representationNarrators, representationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
