// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading_state.sql

package dbsql

import (
	"context"
	"database/sql"
)

const getProgress = `-- name: GetProgress :one
SELECT p.work_id, p.alignment_id, p.segment_id, p.offset, p.revision,
       p.updated_at, p.source_device, a.state AS alignment_state,
       a.state = 'ready' AND s.highlightable = 1 AS resolvable
FROM progress p
JOIN alignments a ON a.id = p.alignment_id
JOIN alignment_segments s ON s.alignment_id = p.alignment_id AND s.id = p.segment_id
WHERE p.user_id = ? AND p.work_id = ?
`

type GetProgressParams struct {
	UserID string
	WorkID string
}

type GetProgressRow struct {
	WorkID         string
	AlignmentID    string
	SegmentID      string
	Offset         int64
	Revision       int64
	UpdatedAt      string
	SourceDevice   string
	AlignmentState string
	Resolvable     sql.NullBool
}

func (q *Queries) GetProgress(ctx context.Context, arg GetProgressParams) (GetProgressRow, error) {
	row := q.db.QueryRowContext(ctx, getProgress, arg.UserID, arg.WorkID)
	var i GetProgressRow
	err := row.Scan(
		&i.WorkID,
		&i.AlignmentID,
		&i.SegmentID,
		&i.Offset,
		&i.Revision,
		&i.UpdatedAt,
		&i.SourceDevice,
		&i.AlignmentState,
		&i.Resolvable,
	)
	return i, err
}

const getProgressRevision = `-- name: GetProgressRevision :one
SELECT revision FROM progress WHERE user_id = ? AND work_id = ?
`

type GetProgressRevisionParams struct {
	UserID string
	WorkID string
}

func (q *Queries) GetProgressRevision(ctx context.Context, arg GetProgressRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProgressRevision, arg.UserID, arg.WorkID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const getRepresentationState = `-- name: GetRepresentationState :one
SELECT representation_id, epub_locator, audio_timestamp_ms, playback_speed_milli,
       reader_layout, zoom_milli, revision, updated_at
FROM representation_state
WHERE user_id = ? AND representation_id = ?
`

type GetRepresentationStateParams struct {
	UserID           string
	RepresentationID string
}

type GetRepresentationStateRow struct {
	RepresentationID   string
	EpubLocator        sql.NullString
	AudioTimestampMs   sql.NullInt64
	PlaybackSpeedMilli sql.NullInt64
	ReaderLayout       sql.NullString
	ZoomMilli          sql.NullInt64
	Revision           int64
	UpdatedAt          string
}

func (q *Queries) GetRepresentationState(ctx context.Context, arg GetRepresentationStateParams) (GetRepresentationStateRow, error) {
	row := q.db.QueryRowContext(ctx, getRepresentationState, arg.UserID, arg.RepresentationID)
	var i GetRepresentationStateRow
	err := row.Scan(
		&i.RepresentationID,
		&i.EpubLocator,
		&i.AudioTimestampMs,
		&i.PlaybackSpeedMilli,
		&i.ReaderLayout,
		&i.ZoomMilli,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepresentationStateRevision = `-- name: GetRepresentationStateRevision :one
SELECT revision FROM representation_state WHERE user_id = ? AND representation_id = ?
`

type GetRepresentationStateRevisionParams struct {
	UserID           string
	RepresentationID string
}

func (q *Queries) GetRepresentationStateRevision(ctx context.Context, arg GetRepresentationStateRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRepresentationStateRevision, arg.UserID, arg.RepresentationID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const upsertProgress = `-- name: UpsertProgress :exec
INSERT INTO progress (user_id, work_id, alignment_id, segment_id, offset, revision, updated_at, source_device)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, work_id) DO UPDATE SET
    alignment_id = excluded.alignment_id,
    segment_id = excluded.segment_id,
    offset = excluded.offset,
    revision = excluded.revision,
    updated_at = excluded.updated_at,
    source_device = excluded.source_device
`

type UpsertProgressParams struct {
	UserID       string
	WorkID       string
	AlignmentID  string
	SegmentID    string
	Offset       int64
	Revision     int64
	UpdatedAt    string
	SourceDevice string
}

func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertProgress,
		arg.UserID,
		arg.WorkID,
		arg.AlignmentID,
		arg.SegmentID,
		arg.Offset,
		arg.Revision,
		arg.UpdatedAt,
		arg.SourceDevice,
	)
	return err
}

const upsertRepresentationState = `-- name: UpsertRepresentationState :exec
INSERT INTO representation_state (
    user_id, representation_id, epub_locator, audio_timestamp_ms,
    playback_speed_milli, reader_layout, zoom_milli, revision, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, representation_id) DO UPDATE SET
    epub_locator = excluded.epub_locator,
    audio_timestamp_ms = excluded.audio_timestamp_ms,
    playback_speed_milli = excluded.playback_speed_milli,
    reader_layout = excluded.reader_layout,
    zoom_milli = excluded.zoom_milli,
    revision = excluded.revision,
    updated_at = excluded.updated_at
`

type UpsertRepresentationStateParams struct {
	UserID             string
	RepresentationID   string
	EpubLocator        sql.NullString
	AudioTimestampMs   sql.NullInt64
	PlaybackSpeedMilli sql.NullInt64
	ReaderLayout       sql.NullString
	ZoomMilli          sql.NullInt64
	Revision           int64
	UpdatedAt          string
}

func (q *Queries) UpsertRepresentationState(ctx context.Context, arg UpsertRepresentationStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepresentationState,
		arg.UserID,
		arg.RepresentationID,
		arg.EpubLocator,
		arg.AudioTimestampMs,
		arg.PlaybackSpeedMilli,
		arg.ReaderLayout,
		arg.ZoomMilli,
		arg.Revision,
		arg.UpdatedAt,
	)
	return err
}

const workForAlignment = `-- name: WorkForAlignment :one
SELECT r.work_id
FROM alignments a
JOIN media m ON m.id = a.epub_media_id
JOIN representations r ON r.id = m.representation_id
WHERE a.id = ?
`

func (q *Queries) WorkForAlignment(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, workForAlignment, id)
	var work_id string
	err := row.Scan(&work_id)
	return work_id, err
}
