// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading_state.sql

package dbsql

import (
	"context"
	"database/sql"
)

const getProgress = `-- name: GetProgress :one
SELECT p.work_id, p.alignment_id, p.segment_id, p.offset, p.revision,
       p.updated_at, p.source_device, a.state AS alignment_state,
       a.state = 'ready' AND s.highlightable = 1 AS resolvable
FROM progress p
JOIN alignments a ON a.id = p.alignment_id
JOIN alignment_segments s ON s.alignment_id = p.alignment_id AND s.id = p.segment_id
WHERE p.user_id = ? AND p.work_id = ?
`

type GetProgressParams struct {
	UserID string
	WorkID string
}

type GetProgressRow struct {
	WorkID         string
	AlignmentID    string
	SegmentID      string
	Offset         int64
	Revision       int64
	UpdatedAt      string
	SourceDevice   string
	AlignmentState string
	Resolvable     sql.NullBool
}

func (q *Queries) GetProgress(ctx context.Context, arg GetProgressParams) (GetProgressRow, error) {
	row := q.db.QueryRowContext(ctx, getProgress, arg.UserID, arg.WorkID)
	var i GetProgressRow
	err := row.Scan(
		&i.WorkID,
		&i.AlignmentID,
		&i.SegmentID,
		&i.Offset,
		&i.Revision,
		&i.UpdatedAt,
		&i.SourceDevice,
		&i.AlignmentState,
		&i.Resolvable,
	)
	return i, err
}

const getProgressRevision = `-- name: GetProgressRevision :one
SELECT revision FROM progress WHERE user_id = ? AND work_id = ?
`

type GetProgressRevisionParams struct {
	UserID string
	WorkID string
}

func (q *Queries) GetProgressRevision(ctx context.Context, arg GetProgressRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getProgressRevision, arg.UserID, arg.WorkID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const getReaderPreferences = `-- name: GetReaderPreferences :one
SELECT reader_layout, zoom_milli, reader_theme, line_height_milli, margin_milli,
       font_family, revision, updated_at
FROM reader_preferences
WHERE user_id = ?
`

type GetReaderPreferencesRow struct {
	ReaderLayout    string
	ZoomMilli       int64
	ReaderTheme     string
	LineHeightMilli int64
	MarginMilli     int64
	FontFamily      string
	Revision        int64
	UpdatedAt       string
}

func (q *Queries) GetReaderPreferences(ctx context.Context, userID string) (GetReaderPreferencesRow, error) {
	row := q.db.QueryRowContext(ctx, getReaderPreferences, userID)
	var i GetReaderPreferencesRow
	err := row.Scan(
		&i.ReaderLayout,
		&i.ZoomMilli,
		&i.ReaderTheme,
		&i.LineHeightMilli,
		&i.MarginMilli,
		&i.FontFamily,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const getReaderPreferencesRevision = `-- name: GetReaderPreferencesRevision :one
SELECT revision FROM reader_preferences WHERE user_id = ?
`

func (q *Queries) GetReaderPreferencesRevision(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getReaderPreferencesRevision, userID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const getRepresentationState = `-- name: GetRepresentationState :one
SELECT representation_id, epub_locator, audio_timestamp_ms, playback_speed_milli,
       reader_layout, zoom_milli, reader_theme, line_height_milli, margin_milli,
       font_family, reader_preferences_override, revision, updated_at
FROM representation_state
WHERE user_id = ? AND representation_id = ?
`

type GetRepresentationStateParams struct {
	UserID           string
	RepresentationID string
}

type GetRepresentationStateRow struct {
	RepresentationID          string
	EpubLocator               sql.NullString
	AudioTimestampMs          sql.NullInt64
	PlaybackSpeedMilli        sql.NullInt64
	ReaderLayout              sql.NullString
	ZoomMilli                 sql.NullInt64
	ReaderTheme               sql.NullString
	LineHeightMilli           sql.NullInt64
	MarginMilli               sql.NullInt64
	FontFamily                sql.NullString
	ReaderPreferencesOverride sql.NullInt64
	Revision                  int64
	UpdatedAt                 string
}

func (q *Queries) GetRepresentationState(ctx context.Context, arg GetRepresentationStateParams) (GetRepresentationStateRow, error) {
	row := q.db.QueryRowContext(ctx, getRepresentationState, arg.UserID, arg.RepresentationID)
	var i GetRepresentationStateRow
	err := row.Scan(
		&i.RepresentationID,
		&i.EpubLocator,
		&i.AudioTimestampMs,
		&i.PlaybackSpeedMilli,
		&i.ReaderLayout,
		&i.ZoomMilli,
		&i.ReaderTheme,
		&i.LineHeightMilli,
		&i.MarginMilli,
		&i.FontFamily,
		&i.ReaderPreferencesOverride,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepresentationStateRevision = `-- name: GetRepresentationStateRevision :one
SELECT revision FROM representation_state WHERE user_id = ? AND representation_id = ?
`

type GetRepresentationStateRevisionParams struct {
	UserID           string
	RepresentationID string
}

func (q *Queries) GetRepresentationStateRevision(ctx context.Context, arg GetRepresentationStateRevisionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getRepresentationStateRevision, arg.UserID, arg.RepresentationID)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const upsertProgress = `-- name: UpsertProgress :exec
INSERT INTO progress (user_id, work_id, alignment_id, segment_id, offset, revision, updated_at, source_device)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, work_id) DO UPDATE SET
    alignment_id = excluded.alignment_id,
    segment_id = excluded.segment_id,
    offset = excluded.offset,
    revision = excluded.revision,
    updated_at = excluded.updated_at,
    source_device = excluded.source_device
`

type UpsertProgressParams struct {
	UserID       string
	WorkID       string
	AlignmentID  string
	SegmentID    string
	Offset       int64
	Revision     int64
	UpdatedAt    string
	SourceDevice string
}

func (q *Queries) UpsertProgress(ctx context.Context, arg UpsertProgressParams) error {
	_, err := q.db.ExecContext(ctx, upsertProgress,
		arg.UserID,
		arg.WorkID,
		arg.AlignmentID,
		arg.SegmentID,
		arg.Offset,
		arg.Revision,
		arg.UpdatedAt,
		arg.SourceDevice,
	)
	return err
}

const upsertReaderPreferences = `-- name: UpsertReaderPreferences :exec
INSERT INTO reader_preferences (
    user_id, reader_layout, zoom_milli, reader_theme, line_height_milli,
    margin_milli, font_family, revision, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id) DO UPDATE SET
    reader_layout = excluded.reader_layout,
    zoom_milli = excluded.zoom_milli,
    reader_theme = excluded.reader_theme,
    line_height_milli = excluded.line_height_milli,
    margin_milli = excluded.margin_milli,
    font_family = excluded.font_family,
    revision = excluded.revision,
    updated_at = excluded.updated_at
`

type UpsertReaderPreferencesParams struct {
	UserID          string
	ReaderLayout    string
	ZoomMilli       int64
	ReaderTheme     string
	LineHeightMilli int64
	MarginMilli     int64
	FontFamily      string
	Revision        int64
	UpdatedAt       string
}

func (q *Queries) UpsertReaderPreferences(ctx context.Context, arg UpsertReaderPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, upsertReaderPreferences,
		arg.UserID,
		arg.ReaderLayout,
		arg.ZoomMilli,
		arg.ReaderTheme,
		arg.LineHeightMilli,
		arg.MarginMilli,
		arg.FontFamily,
		arg.Revision,
		arg.UpdatedAt,
	)
	return err
}

const upsertRepresentationState = `-- name: UpsertRepresentationState :exec
INSERT INTO representation_state (
    user_id, representation_id, epub_locator, audio_timestamp_ms,
    playback_speed_milli, reader_layout, zoom_milli, reader_theme,
    line_height_milli, margin_milli, font_family, reader_preferences_override,
    revision, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(user_id, representation_id) DO UPDATE SET
    epub_locator = COALESCE(excluded.epub_locator, representation_state.epub_locator),
    audio_timestamp_ms = COALESCE(excluded.audio_timestamp_ms, representation_state.audio_timestamp_ms),
    playback_speed_milli = COALESCE(excluded.playback_speed_milli, representation_state.playback_speed_milli),
    reader_layout = COALESCE(excluded.reader_layout, representation_state.reader_layout),
    zoom_milli = COALESCE(excluded.zoom_milli, representation_state.zoom_milli),
    reader_theme = COALESCE(excluded.reader_theme, representation_state.reader_theme),
    line_height_milli = COALESCE(excluded.line_height_milli, representation_state.line_height_milli),
    margin_milli = COALESCE(excluded.margin_milli, representation_state.margin_milli),
    font_family = COALESCE(excluded.font_family, representation_state.font_family),
    reader_preferences_override = COALESCE(excluded.reader_preferences_override, representation_state.reader_preferences_override),
    revision = excluded.revision,
    updated_at = excluded.updated_at
`

type UpsertRepresentationStateParams struct {
	UserID                    string
	RepresentationID          string
	EpubLocator               sql.NullString
	AudioTimestampMs          sql.NullInt64
	PlaybackSpeedMilli        sql.NullInt64
	ReaderLayout              sql.NullString
	ZoomMilli                 sql.NullInt64
	ReaderTheme               sql.NullString
	LineHeightMilli           sql.NullInt64
	MarginMilli               sql.NullInt64
	FontFamily                sql.NullString
	ReaderPreferencesOverride sql.NullInt64
	Revision                  int64
	UpdatedAt                 string
}

func (q *Queries) UpsertRepresentationState(ctx context.Context, arg UpsertRepresentationStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertRepresentationState,
		arg.UserID,
		arg.RepresentationID,
		arg.EpubLocator,
		arg.AudioTimestampMs,
		arg.PlaybackSpeedMilli,
		arg.ReaderLayout,
		arg.ZoomMilli,
		arg.ReaderTheme,
		arg.LineHeightMilli,
		arg.MarginMilli,
		arg.FontFamily,
		arg.ReaderPreferencesOverride,
		arg.Revision,
		arg.UpdatedAt,
	)
	return err
}

const workForAlignment = `-- name: WorkForAlignment :one
SELECT r.work_id
FROM alignments a
JOIN media m ON m.id = a.epub_media_id
JOIN representations r ON r.id = m.representation_id
WHERE a.id = ?
`

func (q *Queries) WorkForAlignment(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, workForAlignment, id)
	var work_id string
	err := row.Scan(&work_id)
	return work_id, err
}
